version: "3"
services:
  frontend_dev:
    image: "lsj20605/frontend"
    container_name: "frontend_dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend_dev
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server --port 6379 --bind 0.0.0.0 --protected-mode no
    ports:
      - 6379:6379
  database:
    container_name: "database"
    image: "mysql:8.0.30"
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/db/conf.d:/etc/mysql/conf.d
      - /home/ubuntu/db/data:/var/lib/mysql
      - /home/ubuntu/db/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_DATABASE=zipSoft
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - db_network
  backend_dev:
    image: "lsj20605/zipsoft"
    container_name: "backend_dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/home/ubuntu/logs/backend:/data/logs"
      - "/home/ubuntu/upload:/data/upload"  
    networks:
      - db_network
    depends_on:
      - redis

networks:
  db_network:
    driver: bridge
    external: true
    internal: true