version: "3"
services:
  frontend_local:
    image: "lsj20605/frontend"
    container_name: "frontend_local"
    build:
      context: "/frontend"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend_local
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server --port 6379 --bind 0.0.0.0 --protected-mode no
    ports:
      - 6379:6379
    networks:
      - redis_network
  database:
    container_name: "database"
    image: "mysql:8.0.30"
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/user/Documents/db/conf.d:/etc/mysql/conf.d
      - C:/Users/user/Documents/db/data:/var/lib/mysql
      - C:/Users/user/Documents/db/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_DATABASE=zipSoft
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - db_network
  backend_local:
    image: "lsj20605/zipsoft"
    container_name: "backend_local"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/user/Documents/logs:/data2/potal/logs"  
    networks:
      - db_network
      - redis_network
    depends_on:
      - redis

networks:
  db_network:
    driver: bridge
  redis_network:
    driver: bridge