version: "3"
services:
  frontend:
    image: "lsj20605/frontend"
    container_name: "frontend_dev"
    build:
      context: "/frontend"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server --port 6379 --bind 0.0.0.0 --protected-mode no
    ports:
      - 6379:6379
  backend:
    image: "lsj20605/zipsoft"
    container_name: "backend_dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/user/Documents/logs:/data2/potal/logs"  
    depends_on:
      - redis