server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/zipsoft?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: admin
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      
      
app:
  jwt:
    jwtSecret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345WETsdfg1234vxsd32QWRSDGGSDGSwetSDFWETW123124856XGBFSDGS
    jwtExpirationInMs: 30
    jwtRefreshExpriationInMs: 120