server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
      
spring:
  data:
    rest:
      default-page-size: 10
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 150MB
      max-request-size: 150MB
        
  
app:
  jwt:
    jwtSecret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345WETsdfg1234vxsd32QWRSDGGSDGSwetSDFWETW123124856XGBFSDGS
    jwtExpirationInMs: 30
    jwtRefreshExpriationInMs: 120